# Generated by Django 3.0.1 on 2020-08-23 18:05

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReuqestList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestType', multiselectfield.db.fields.MultiSelectField(choices=[('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Painting', 'Painting'), ('Deep Cleaning', 'Deep Cleaning')], max_length=50)),
                ('RequestDesc', models.CharField(max_length=50)),
                ('RequestDate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=15)),
                ('pin', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(choices=[('Andra', 'Andra'), ('Pradesh', 'Pradesh'), ('Arunachal', 'Arunachal'), ('Pradesh', 'Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal', 'Himachal'), ('Pradesh', 'Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madya', 'Madya'), ('Pradesh', 'Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Orissa', 'Orissa'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil', 'Tamil'), ('Nadu', 'Nadu'), ('Telagana', 'Telagana'), ('Tripura', 'Tripura'), ('Uttaranchal', 'Uttaranchal'), ('Uttar', 'Uttar'), ('Pradesh', 'Pradesh'), ('West', 'West'), ('Bengal', 'Bengal')], max_length=40)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('Remarks', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StateName', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='YourLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('password', models.TextField()),
                ('last_login', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
